[project]
name = 'test_project_1'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.hello-stacks]
path = 'contracts/hello-stacks.clar'
clarity_version = 3
epoch = 3.0

[contracts.minting_test]
path = 'contracts/minting_test.clar'
clarity_version = 3
epoch = 3.0

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
